"""
event_calendar.py -- Economic event calendar with forward-looking analysis.

Sources:
- Bank of Canada: rate decision dates (published annually)
- Statistics Canada: release calendar (recurring monthly schedule)
- Provincial budget dates (announced weeks in advance)
- IAAC/CER hearing dates for major projects (from Firestore)

Pre-event analysis generated by Claude Sonnet for high-significance events.
"""

import json
import logging
from datetime import datetime, timedelta

logger = logging.getLogger(__name__)

# ── Bank of Canada fixed announcement dates ──────────────────────────
# Update each January from https://www.bankofcanada.ca/core-functions/monetary-policy/key-interest-rate/

BOC_RATE_DECISIONS_2026 = [
    "2026-01-29", "2026-03-12", "2026-04-16", "2026-06-04",
    "2026-07-09", "2026-09-17", "2026-10-22", "2026-12-10",
]

# ── StatsCan recurring releases ──────────────────────────────────────

STATCAN_RECURRING = [
    {
        "name": "Labour Force Survey",
        "frequency": "monthly",
        "typical_week_day": "friday",
        "typical_week": 1,  # first week of month
        "indicator": "employment",
        "significance": "high",
        "relevance": "Employment and unemployment by province. Affects infrastructure spending pressure and construction labour availability.",
    },
    {
        "name": "Consumer Price Index",
        "frequency": "monthly",
        "typical_week_day": "tuesday",
        "typical_week": 3,
        "indicator": "cpi_total",
        "significance": "high",
        "relevance": "Inflation reading. Directly influences BoC rate path and project financing costs.",
    },
    {
        "name": "GDP by Industry",
        "frequency": "monthly",
        "typical_week_day": "friday",
        "typical_week": 4,  # last week
        "indicator": "gdp_monthly",
        "significance": "medium",
        "relevance": "Economic growth breakdown. Construction and mining sectors directly reported.",
    },
    {
        "name": "Building Permits",
        "frequency": "monthly",
        "typical_week_day": "variable",
        "typical_week": 2,
        "indicator": "building_permits",
        "significance": "medium",
        "relevance": "6-12 month leading indicator of construction activity by province.",
    },
    {
        "name": "Housing Starts (CMHC)",
        "frequency": "monthly",
        "typical_week_day": "variable",
        "typical_week": 3,
        "indicator": "housing_starts",
        "significance": "medium",
        "relevance": "Current residential construction activity level.",
    },
    {
        "name": "Investment in Building Construction",
        "frequency": "monthly",
        "indicator": "investment_nonresidential",
        "significance": "medium",
        "relevance": "Directly measures capital spending on non-residential construction.",
    },
]

# ── Provincial budget season (typically Feb-April) ───────────────────

PROVINCIAL_BUDGETS_2026 = [
    {"province": "AB", "expected": "February 2026", "confirmed_date": None},
    {"province": "BC", "expected": "February 2026", "confirmed_date": None},
    {"province": "ON", "expected": "March 2026", "confirmed_date": None},
    {"province": "QC", "expected": "March 2026", "confirmed_date": None},
    {"province": "MB", "expected": "April 2026", "confirmed_date": None},
    {"province": "SK", "expected": "March 2026", "confirmed_date": None},
    {"province": "NS", "expected": "March 2026", "confirmed_date": None},
    {"province": "NB", "expected": "March 2026", "confirmed_date": None},
    {"province": "NL", "expected": "April 2026", "confirmed_date": None},
    {"province": "PEI", "expected": "April 2026", "confirmed_date": None},
    {"province": "federal", "expected": "April 2026", "confirmed_date": None},
]


def _estimate_statcan_date(release, ref_month):
    """Estimate the date of a recurring StatsCan release for a given month."""
    year = ref_month.year
    month = ref_month.month
    week = release.get("typical_week", 2)
    # Approximate: week N of month = day 7*(N-1)+3
    day = min(7 * (week - 1) + 3, 28)
    try:
        return datetime(year, month, day).date()
    except ValueError:
        return datetime(year, month, 15).date()


def get_upcoming_events(db=None, days_ahead=14):
    """Get economic events in the next N days.

    Args:
        db: optional Firestore client (for project hearing dates)
        days_ahead: how far ahead to look

    Returns:
        sorted list of event dicts
    """
    today = datetime.utcnow().date()
    cutoff = today + timedelta(days=days_ahead)
    events = []

    # BoC rate decisions
    for date_str in BOC_RATE_DECISIONS_2026:
        try:
            event_date = datetime.strptime(date_str, "%Y-%m-%d").date()
        except ValueError:
            continue
        if today <= event_date <= cutoff:
            events.append({
                "date": date_str,
                "name": "Bank of Canada Rate Decision",
                "source": "Bank of Canada",
                "type": "rate_decision",
                "significance": "high",
                "indicators_affected": ["policy_rate", "mortgage_5y_fixed", "prime_rate"],
                "sectors_affected": ["Real Estate", "Construction", "Finance"],
                "relevance": "Rate decisions directly affect mortgage rates, project financing costs, and housing market activity.",
            })

    # StatsCan recurring releases -- check next 2 months
    for release in STATCAN_RECURRING:
        for month_offset in range(3):
            ref_month = datetime(today.year, today.month, 1) + timedelta(days=30 * month_offset)
            est_date = _estimate_statcan_date(release, ref_month)
            if today <= est_date <= cutoff:
                events.append({
                    "date": est_date.isoformat(),
                    "name": release["name"],
                    "source": "Statistics Canada",
                    "type": "data_release",
                    "frequency": release["frequency"],
                    "significance": release.get("significance", "medium"),
                    "indicator": release["indicator"],
                    "relevance": release["relevance"],
                })
                break  # only add one occurrence per release

    # Provincial budgets
    for budget in PROVINCIAL_BUDGETS_2026:
        if budget.get("confirmed_date"):
            try:
                event_date = datetime.strptime(budget["confirmed_date"], "%Y-%m-%d").date()
            except ValueError:
                continue
            if today <= event_date <= cutoff:
                events.append({
                    "date": budget["confirmed_date"],
                    "name": f"{budget['province']} Provincial Budget",
                    "source": f"{budget['province']} Finance Ministry",
                    "type": "budget",
                    "significance": "high",
                    "province": budget["province"],
                    "relevance": f"Provincial budget may include capital spending allocations, tax incentives, and infrastructure funding for {budget['province']}.",
                })

    events.sort(key=lambda x: x.get("date", "9999"))
    return events


async def generate_pre_event_analysis(event, indicator_history, project_data):
    """Generate forward-looking analysis for an upcoming economic event via Claude Sonnet."""
    from claude_reasoning import reason_with_claude_tracked

    system = (
        "You are a Canadian economic analyst preparing a forward-looking briefing "
        "ahead of a major economic event. State what the event is, summarize "
        "market expectations, explain what each outcome would mean for capital "
        "investment, identify specific affected projects, and reference historical "
        "precedent. Be concise (150-250 words)."
    )

    user_prompt = f"""UPCOMING EVENT:
{json.dumps(event, indent=2)}

HISTORICAL CONTEXT:
{json.dumps(indicator_history, indent=2)}

PROJECTS IN AFFECTED SECTORS:
{json.dumps([{
    'name': p.get('name'),
    'province': p.get('province') or (p.get('location', {}) or {}).get('province'),
    'sector': p.get('sector'),
    'value_millions': p.get('value_millions'),
    'status': p.get('status'),
} for p in project_data[:15]], indent=2)}

Generate a pre-event analysis for our weekly briefing. What should readers
watch for, and what would different outcomes mean for the capital project pipeline?"""

    return await reason_with_claude_tracked(
        system, user_prompt,
        task_name=f"pre_event_{event.get('type', 'unknown')}",
        max_tokens=1500,
    )


def get_and_store_events(db, days_ahead=14):
    """Main entry point: get upcoming events and store in Firestore.

    Returns list of upcoming events.
    """
    print(f"\n[CALENDAR] Checking events in next {days_ahead} days...")
    events = get_upcoming_events(db, days_ahead)

    if not events:
        print("  [CALENDAR] No upcoming events")
        return []

    print(f"  [CALENDAR] {len(events)} upcoming events:")
    for e in events:
        sig = e.get("significance", "?")
        print(f"    [{sig.upper()}] {e.get('date', '?')} - {e['name']}")

    # Store in Firestore
    if db:
        try:
            db.collection("dashboard_state").document("upcoming_events").set({
                "events": events,
                "updated_at": datetime.utcnow().isoformat(),
                "days_ahead": days_ahead,
            })
        except Exception as e:
            logger.warning(f"Failed to store events: {e}")

    return events
