"""
event_calendar.py -- Economic event calendar with forward-looking analysis.

Sources:
- Bank of Canada: rate decision dates (published annually)
- Statistics Canada: release calendar (recurring monthly schedule)
- Provincial budget dates (announced weeks in advance)
- IAAC/CER hearing dates for major projects (from Firestore)

Pre-event analysis generated by Claude Sonnet for high-significance events.
"""

import json
import logging
from datetime import datetime, timedelta

logger = logging.getLogger(__name__)

# ── Bank of Canada fixed announcement dates ──────────────────────────
# Update each January from https://www.bankofcanada.ca/core-functions/monetary-policy/key-interest-rate/

BOC_RATE_DECISIONS_2026 = [
    "2026-01-29", "2026-03-12", "2026-04-16", "2026-06-04",
    "2026-07-09", "2026-09-17", "2026-10-22", "2026-12-10",
]

# ── StatsCan recurring releases ──────────────────────────────────────

STATCAN_RECURRING = [
    {
        "name": "Labour Force Survey",
        "frequency": "monthly",
        "typical_week_day": "friday",
        "typical_week": 1,  # first week of month
        "indicator": "employment",
        "significance": "high",
        "relevance": "Employment and unemployment by province. Affects infrastructure spending pressure and construction labour availability.",
        # Canonical StatCan headline LFS table (14-10-0287, monthly SA + trend-cycle).
        "url": "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410028701",
    },
    {
        "name": "Consumer Price Index",
        "frequency": "monthly",
        "typical_week_day": "tuesday",
        "typical_week": 3,
        "indicator": "cpi_total",
        "significance": "high",
        "relevance": "Inflation reading. Directly influences BoC rate path and project financing costs.",
        # Canonical StatCan headline CPI table (18-10-0004, monthly).
        "url": "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401",
    },
    {
        "name": "GDP by Industry",
        "frequency": "monthly",
        "typical_week_day": "friday",
        "typical_week": 4,  # last week
        "indicator": "gdp_monthly",
        "significance": "medium",
        "relevance": "Economic growth breakdown. Construction and mining sectors directly reported.",
        # Canonical StatCan monthly GDP-by-industry table (36-10-0434).
        "url": "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610043401",
    },
    {
        "name": "Building Permits",
        "frequency": "monthly",
        "typical_week_day": "variable",
        "typical_week": 2,
        "indicator": "building_permits",
        "significance": "medium",
        "relevance": "6-12 month leading indicator of construction activity by province.",
        # Canonical StatCan monthly Building Permits table (34-10-0066).
        "url": "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410006601",
    },
    {
        "name": "Housing Starts (CMHC)",
        "frequency": "monthly",
        "typical_week_day": "variable",
        "typical_week": 3,
        "indicator": "housing_starts",
        "significance": "medium",
        "relevance": "Current residential construction activity level.",
        # Canonical StatCan housing starts table (34-10-0143, monthly).
        "url": "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410014301",
    },
    {
        "name": "Investment in Building Construction",
        "frequency": "monthly",
        "indicator": "investment_nonresidential",
        "significance": "medium",
        "relevance": "Directly measures capital spending on non-residential construction.",
        # Canonical StatCan investment-in-building-construction table (34-10-0175).
        "url": "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3410017501",
    },
]

# Bank of Canada rate decision schedule permalink — always resolves to the
# current year's announcement dates.
BOC_RATE_DECISION_URL = (
    "https://www.bankofcanada.ca/core-functions/monetary-policy/"
    "key-interest-rate/"
)

# Official finance-ministry / budget-portal landing pages. Stable permalinks.
PROVINCIAL_BUDGET_URLS = {
    "federal": "https://www.budget.canada.ca/",
    "AB": "https://www.alberta.ca/budget.aspx",
    "BC": "https://www.bcbudget.gov.bc.ca/",
    "ON": "https://budget.ontario.ca/",
    "QC": "https://www.budget.finances.gouv.qc.ca/",
    "MB": "https://www.gov.mb.ca/finance/budget/",
    "SK": "https://www.saskatchewan.ca/government/budget-planning-and-reporting",
    "NS": "https://beta.novascotia.ca/budget",
    "NB": "https://www2.gnb.ca/content/gnb/en/departments/finance/budget.html",
    "NL": "https://www.gov.nl.ca/fin/budget/",
    "PEI": "https://www.princeedwardisland.ca/en/topic/budget",
    "NT": "https://www.fin.gov.nt.ca/en/services/budget-and-fiscal-planning",
    "YT": "https://yukon.ca/en/budget",
    "NU": "https://www.gov.nu.ca/finance/information/budget-documents",
}

# ── Provincial budget season (typically Feb-April) ───────────────────

PROVINCIAL_BUDGETS_2026 = [
    {"province": "AB", "expected": "February 2026", "confirmed_date": None},
    {"province": "BC", "expected": "February 2026", "confirmed_date": None},
    {"province": "ON", "expected": "March 2026", "confirmed_date": None},
    {"province": "QC", "expected": "March 2026", "confirmed_date": None},
    {"province": "MB", "expected": "April 2026", "confirmed_date": None},
    {"province": "SK", "expected": "March 2026", "confirmed_date": None},
    {"province": "NS", "expected": "March 2026", "confirmed_date": None},
    {"province": "NB", "expected": "March 2026", "confirmed_date": None},
    {"province": "NL", "expected": "April 2026", "confirmed_date": None},
    {"province": "PEI", "expected": "April 2026", "confirmed_date": None},
    {"province": "federal", "expected": "April 2026", "confirmed_date": None},
]


def _estimate_statcan_date(release, ref_month):
    """Estimate the date of a recurring StatsCan release for a given month."""
    year = ref_month.year
    month = ref_month.month
    week = release.get("typical_week", 2)
    # Approximate: week N of month = day 7*(N-1)+3
    day = min(7 * (week - 1) + 3, 28)
    try:
        return datetime(year, month, day).date()
    except ValueError:
        return datetime(year, month, 15).date()


_PROVINCE_CODES = ["AB", "BC", "MB", "NB", "NL", "NS", "NT", "NU", "ON", "PE", "QC", "SK", "YT"]

_PROV_FULL_NAMES = {
    "AB": "Alberta", "BC": "British Columbia", "MB": "Manitoba",
    "NB": "New Brunswick", "NL": "Newfoundland and Labrador",
    "NS": "Nova Scotia", "NT": "Northwest Territories", "NU": "Nunavut",
    "ON": "Ontario", "PE": "Prince Edward Island", "QC": "Quebec",
    "SK": "Saskatchewan", "YT": "Yukon",
}


def get_upcoming_events(conn=None, days_ahead=14, db=None):
    """Get economic events in the next N days, including province-specific events.

    Args:
        conn: optional sqlite3.Connection for province event lookups
        days_ahead: how far ahead to look
        db: deprecated Firestore client; ignored (kept for backward compatibility)

    Returns:
        sorted list of event dicts, each with a 'province' field
    """
    today = datetime.utcnow().date()
    cutoff = today + timedelta(days=days_ahead)
    events = []

    # BoC rate decisions — national, affects all provinces
    for date_str in BOC_RATE_DECISIONS_2026:
        try:
            event_date = datetime.strptime(date_str, "%Y-%m-%d").date()
        except ValueError:
            continue
        if today <= event_date <= cutoff:
            events.append({
                "date": date_str,
                "name": "Bank of Canada Rate Decision",
                "source": "Bank of Canada",
                "type": "rate_decision",
                "significance": "high",
                "province": "national",
                "provinces_affected": _PROVINCE_CODES,
                "indicators_affected": ["policy_rate", "mortgage_5y_fixed", "prime_rate"],
                "sectors_affected": ["Real Estate", "Construction", "Finance"],
                "relevance": "Rate decisions directly affect mortgage rates, project financing costs, and housing market activity.",
                "url": BOC_RATE_DECISION_URL,
            })

    # StatsCan recurring releases — national, affects all provinces
    for release in STATCAN_RECURRING:
        for month_offset in range(3):
            ref_month = datetime(today.year, today.month, 1) + timedelta(days=30 * month_offset)
            est_date = _estimate_statcan_date(release, ref_month)
            if today <= est_date <= cutoff:
                events.append({
                    "date": est_date.isoformat(),
                    "name": release["name"],
                    "source": "Statistics Canada",
                    "type": "data_release",
                    "frequency": release["frequency"],
                    "significance": release.get("significance", "medium"),
                    "province": "national",
                    "provinces_affected": _PROVINCE_CODES,
                    "indicator": release["indicator"],
                    "relevance": release["relevance"],
                    "url": release.get("url", ""),
                })
                break  # only add one occurrence per release

    # Provincial budgets — emit both confirmed and unconfirmed
    for budget in PROVINCIAL_BUDGETS_2026:
        prov = budget["province"]
        if budget.get("confirmed_date"):
            try:
                event_date = datetime.strptime(budget["confirmed_date"], "%Y-%m-%d").date()
            except ValueError:
                continue
            if today <= event_date <= cutoff:
                label = "Federal Budget" if prov == "federal" else f"{prov} Provincial Budget"
                events.append({
                    "date": budget["confirmed_date"],
                    "name": label,
                    "source": f"{prov} Finance Ministry",
                    "type": "budget",
                    "significance": "high",
                    "province": prov if prov != "federal" else "national",
                    "relevance": f"Budget may include capital spending allocations, tax incentives, and infrastructure funding for {prov}.",
                    "url": PROVINCIAL_BUDGET_URLS.get(prov, ""),
                })
        else:
            # Emit unconfirmed budget with estimated month
            expected = budget.get("expected", "")
            if expected:
                try:
                    est_date = datetime.strptime(expected, "%B %Y").date()
                    # Use mid-month as estimate
                    est_date = est_date.replace(day=15)
                    if today <= est_date <= cutoff:
                        label = "Federal Budget (est.)" if prov == "federal" else f"{prov} Provincial Budget (est.)"
                        events.append({
                            "date": est_date.isoformat(),
                            "name": label,
                            "source": f"{prov} Finance Ministry",
                            "type": "budget",
                            "significance": "medium",
                            "province": prov if prov != "federal" else "national",
                            "relevance": f"Expected {expected}. Date not yet confirmed.",
                            "url": PROVINCIAL_BUDGET_URLS.get(prov, ""),
                        })
                except ValueError:
                    pass

    # Pipeline-sourced province events (policy, IAAC)
    if conn:
        pipeline_events = get_pipeline_province_events(conn, days_ahead)
        events.extend(pipeline_events)

    # Tavily-sourced province events (cached)
    if conn:
        tavily_events = get_cached_province_events(conn, days_ahead)
        events.extend(tavily_events)

    # Curation gate (2026-06-15 fix): events.json must contain only material
    # *scheduled* events. Two upstream leaks polluted the calendar with run-date-
    # stamped noise that masqueraded as "upcoming":
    #   - search_province_events() emits raw Tavily web-search hits as
    #     type='watchlist' / significance='low' (e.g. "... - Facebook",
    #     "[PDF] TD Economics - 2026 Alberta Budget"), all stamped date=today.
    #   - get_pipeline_province_events() emits weekly policy bulletins as
    #     type='policy' / significance='medium', also stamped date=today (not a
    #     real future event date).
    # Keep the curated structural events (BoC rate decisions, StatCan releases,
    # budgets) regardless of date; drop search-result noise and any remaining
    # run-date-stamped low-signal rows so only genuine upcoming events show.
    today_iso = today.isoformat()
    _SCHEDULED_TYPES = {"rate_decision", "data_release", "budget"}

    def _is_material_event(ev):
        etype = str(ev.get("type") or "").lower()
        sig = str(ev.get("significance") or "").lower()
        if etype == "watchlist":
            return False                      # Tavily/Google search-result noise
        if etype in _SCHEDULED_TYPES:
            return True                       # real BoC / StatCan / budget dates
        if sig == "low":
            return False
        # Remaining rows (e.g. pipeline 'policy') must be genuinely upcoming,
        # not run-date-stamped current-week news.
        return str(ev.get("date") or "") > today_iso

    events = [e for e in events if _is_material_event(e)]
    events.sort(key=lambda x: x.get("date", "9999"))
    return events


def get_pipeline_province_events(conn, days_ahead=14):
    """Extract province-specific events from pipeline data (zero cost).

    Sources: policy_snapshots (legislative/regulatory items)
    """
    events = []
    today = datetime.utcnow().date()

    # Policy items with province tags
    try:
        row = conn.execute(
            "SELECT data FROM policy_snapshots ORDER BY week_of DESC LIMIT 1"
        ).fetchone()
        if row:
            items = json.loads(row[0]) if isinstance(row[0], str) else row[0]
            for item in (items or []):
                province = item.get("province")
                if not province:
                    continue
                # Policy items are recent legislative/regulatory developments
                title = item.get("title", "")
                if not title:
                    continue
                categories = item.get("policy_categories", [])
                cat_label = categories[0].replace("_", " ").title() if categories else "Policy"
                events.append({
                    "date": today.isoformat(),  # Current week
                    "name": f"{cat_label}: {title[:80]}",
                    "source": item.get("source_description", "Government"),
                    "type": "policy",
                    "significance": "medium",
                    "province": province,
                    "url": item.get("url", ""),
                    "relevance": item.get("summary", "")[:200],
                })
    except Exception as e:
        logger.warning(f"Pipeline province events (policy): {e}")

    return events


def get_cached_province_events(conn, days_ahead=14):
    """Get Tavily-sourced province events from cache.

    Cache is stored in dashboard_state with key 'province_events_cache'.
    Expires after 7 days.
    """
    try:
        from db import get_dashboard_state
        cache = get_dashboard_state(conn, "province_events_cache")
        if not cache:
            return []
        # Check cache freshness
        cached_date = cache.get("date", "")
        if cached_date:
            try:
                cache_dt = datetime.strptime(cached_date, "%Y-%m-%d").date()
                if (datetime.utcnow().date() - cache_dt).days > 7:
                    return []  # Stale cache
            except ValueError:
                pass
        return cache.get("events", [])
    except Exception as e:
        logger.warning(f"Province events cache read failed: {e}")
        return []


def search_province_events(conn, days_ahead=30):
    """Search for province-specific upcoming events via Tavily.

    Uses ~50 Tavily credits (5 per province for 10 provinces).
    Results cached in dashboard_state for 7 days.

    Args:
        conn: SQLite connection for caching results
        days_ahead: how far ahead to include events

    Returns:
        list of event dicts with province field
    """
    from tavily_search import tavily_search_sync, can_use_tavily
    from db import save_dashboard_state

    if not can_use_tavily():
        print("  [CALENDAR] Tavily budget exhausted, skipping province event search")
        return []

    today = datetime.utcnow().date()
    year = today.year
    events = []

    # Search national + each province
    search_targets = [("national", "Canada")] + [
        (code, _PROV_FULL_NAMES[code]) for code in
        ["ON", "QC", "AB", "BC", "SK", "MB", "NS", "NB", "NL", "PE"]
    ]

    for prov_code, prov_name in search_targets:
        if not can_use_tavily():
            break
        query = f'upcoming economic events budget policy announcement {prov_name} Canada {year}'
        try:
            results = tavily_search_sync(query, max_results=5, search_depth="basic")
            for r in (results or []):
                title = r.get("title", "")
                if not title:
                    continue
                events.append({
                    "date": today.isoformat(),  # Approximate — exact date from content
                    "name": title[:100],
                    "source": r.get("url", "").split("/")[2] if "/" in r.get("url", "") else "Web",
                    "type": "watchlist",
                    "significance": "low",
                    "province": prov_code,
                    "url": r.get("url", ""),
                    "relevance": (r.get("content", "") or "")[:200],
                })
            print(f"  [CALENDAR] {prov_name}: {len(results or [])} results")
        except Exception as e:
            logger.warning(f"Province event search ({prov_name}): {e}")

    # Cache results
    try:
        save_dashboard_state(conn, "province_events_cache", {
            "date": today.isoformat(),
            "events": events,
        })
        print(f"  [CALENDAR] Cached {len(events)} province events")
    except Exception as e:
        logger.warning(f"Province events cache write failed: {e}")

    return events


async def generate_pre_event_analysis(event, indicator_history, project_data):
    """Generate forward-looking analysis for an upcoming economic event via Claude Sonnet."""
    from claude_reasoning import reason_with_claude_tracked

    system = (
        "You are a Canadian economic analyst preparing a forward-looking briefing "
        "ahead of a major economic event. State what the event is, summarize "
        "market expectations, explain what each outcome would mean for capital "
        "investment, identify specific affected projects, and reference historical "
        "precedent. Be concise (150-250 words)."
    )

    user_prompt = f"""UPCOMING EVENT:
{json.dumps(event, indent=2)}

HISTORICAL CONTEXT:
{json.dumps(indicator_history, indent=2)}

PROJECTS IN AFFECTED SECTORS:
{json.dumps([{
    'name': p.get('name'),
    'province': p.get('province') or (p.get('location', {}) or {}).get('province'),
    'sector': p.get('sector'),
    'value_millions': p.get('value_millions'),
    'status': p.get('status'),
} for p in project_data[:15]], indent=2)}

Generate a pre-event analysis for our weekly briefing. What should readers
watch for, and what would different outcomes mean for the capital project pipeline?"""

    from claude_reasoning import OPUS_WRITING_MODEL
    return await reason_with_claude_tracked(
        system, user_prompt,
        task_name=f"pre_event_{event.get('type', 'unknown')}",
        max_tokens=1500,
        model=OPUS_WRITING_MODEL,
    )


def get_and_store_events(conn=None, days_ahead=14, db=None):
    """Main entry point: get upcoming events and store in SQLite.

    Args:
        conn: sqlite3.Connection from db.py (preferred)
        days_ahead: how far ahead to look
        db: deprecated Firestore client; ignored (kept for backward compatibility)

    Returns list of upcoming events.
    """
    print(f"\n[CALENDAR] Checking events in next {days_ahead} days...")
    events = get_upcoming_events(days_ahead=days_ahead)

    if not events:
        print("  [CALENDAR] No upcoming events")
        return []

    print(f"  [CALENDAR] {len(events)} upcoming events:")
    for e in events:
        sig = e.get("significance", "?")
        print(f"    [{sig.upper()}] {e.get('date', '?')} - {e['name']}")

    # Store in SQLite
    if conn and hasattr(conn, 'execute'):
        try:
            from db import save_dashboard_state
            save_dashboard_state(conn, "upcoming_events", {
                "events": events,
                "updated_at": datetime.utcnow().isoformat(),
                "days_ahead": days_ahead,
            })
        except Exception as e:
            logger.warning(f"Failed to store events: {e}")

    return events
