-- Patch 1.2 — migration 001  (NEUTRALIZED — DO NOT RUN THE OLD REMAP)
-- audit ref: D-4 / DI-5 (status vocabulary reconciliation)
--
-- ─────────────────────────────────────────────────────────────────────────────
-- WHY THIS IS A NO-OP
-- ─────────────────────────────────────────────────────────────────────────────
-- The 2026-06-08 CONSOLIDATED audit REFUTED the original D-4 "status drift" claim
-- as a data-integrity bug. Every status in dashboard.db is already a member of the
-- canonical set defined by normalize.py (the operational single source of truth):
--
--     Proposed · Under Review · Approved · Under Construction ·
--     Partially Complete · Complete · Cancelled · On Hold
--
-- The DB is SELF-CONSISTENT. The earlier draft of this migration mapped the
-- OPPOSITE direction (Proposed -> Announced, Complete -> Completed, On Hold ->
-- Paused) toward a *different* documented vocabulary. Running it would have:
--   * relabelled 2,698 correct 'Proposed' rows to 'Announced',
--   * relabelled 510 'Complete' -> 'Completed', 31 'On Hold' -> 'Paused', and
--   * (via the old catch-all) risked collapsing other legitimate tiers,
-- splitting the vocabulary against normalize.py and the live code path, which then
-- re-drifts every run. See DI-5 in PROJECT_AUDIT_2026-06-08_consolidated.md.
--
-- FIX (code, not data): project_schema.normalize_status now DELEGATES to
-- normalize.normalize_status, so the upsert boundary canonicalizes to the SAME
-- vocabulary the existing rows use. No DB backfill is required or wanted.
--
-- If you ever need to AUDIT (not change) status values, run read-only:
--   SELECT status, COUNT(*) FROM projects GROUP BY status ORDER BY 2 DESC;
-- Expected: only the eight normalize.py-canonical statuses above.

-- Intentionally no UPDATE statements. This migration performs no changes.
SELECT 'migration 001 is a no-op (DI-5): DB already canonical per normalize.py' AS note;
